"""initial schema

Revision ID: 45637c8d2927
Revises: 
Create Date: 2026-07-25 23:26:09.585048
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '45637c8d2927'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competency',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('parent', sa.String(length=8), nullable=False),
    sa.Column('skill', sa.Enum('vocabulary', 'grammar', 'pronunciation', 'fluency', name='skill', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('cefr_min', sa.Enum('A2', 'B1', 'B2', 'C1', 'C2', name='cefr_min', native_enum=False), nullable=False),
    sa.Column('cefr_max', sa.Enum('A2', 'B1', 'B2', 'C1', 'C2', name='cefr_max', native_enum=False), nullable=False),
    sa.Column('observable', sa.Boolean(), nullable=False),
    sa.Column('success_criteria', sa.Text(), nullable=True),
    sa.Column('elicitation_cues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('l1_risk_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('l1_confusions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('measurement', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competency_parent'), 'competency', ['parent'], unique=False)
    op.create_table('domain',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('cefr', sa.Enum('A2', 'B1', 'B2', 'C1', 'C2', name='domain_cefr', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('life_path',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('vocabulary_overlay_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('family', sa.String(length=64), nullable=False),
    sa.Column('stimulus_type', sa.String(length=32), nullable=False),
    sa.Column('interaction_mode', sa.String(length=16), nullable=False),
    sa.Column('cefr_min', sa.Enum('A2', 'B1', 'B2', 'C1', 'C2', name='template_cefr_min', native_enum=False), nullable=False),
    sa.Column('cefr_max', sa.Enum('A2', 'B1', 'B2', 'C1', 'C2', name='template_cefr_max', native_enum=False), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('duration_max', sa.Integer(), nullable=False),
    sa.Column('scaffold_ladder_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competency_error',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competency_id', sa.String(length=16), nullable=False),
    sa.Column('wrong', sa.Text(), nullable=False),
    sa.Column('right', sa.Text(), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competency.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competency_error_competency_id'), 'competency_error', ['competency_id'], unique=False)
    op.create_index(op.f('ix_competency_error_tag'), 'competency_error', ['tag'], unique=False)
    op.create_table('competency_prereq',
    sa.Column('competency_id', sa.String(length=16), nullable=False),
    sa.Column('requires_id', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competency.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requires_id'], ['competency.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('competency_id', 'requires_id')
    )
    op.create_table('dimension',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('fixed', sa.Boolean(), nullable=False),
    sa.Column('life_path_id', sa.String(length=48), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint('(fixed and life_path_id is null) or (not fixed and life_path_id is not null)', name='dimension_fixed_xor_path_check'),
    sa.ForeignKeyConstraint(['life_path_id'], ['life_path.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dimension_life_path_id'), 'dimension', ['life_path_id'], unique=False)
    op.create_table('domain_context',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain_id', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_context_domain_id'), 'domain_context', ['domain_id'], unique=False)
    op.create_table('domain_objective',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain_id', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domain_objective_domain_id'), 'domain_objective', ['domain_id'], unique=False)
    op.create_table('domain_requires',
    sa.Column('domain_id', sa.String(length=16), nullable=False),
    sa.Column('competency_id', sa.String(length=16), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('explicit_subs_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("role in ('core','supporting','incidental')", name='domain_requires_role_check'),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('domain_id', 'competency_id')
    )
    op.create_table('learner_profile',
    sa.Column('learner_id', sa.String(length=48), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('cefr', sa.Enum('A2', 'B1', 'B2', 'C1', 'C2', name='learner_cefr', native_enum=False), nullable=False),
    sa.Column('l1', sa.String(length=8), nullable=False),
    sa.Column('life_path_id', sa.String(length=48), nullable=False),
    sa.Column('study_field', sa.String(length=120), nullable=True),
    sa.Column('daily_minutes', sa.Integer(), nullable=False),
    sa.Column('feedback_language', sa.String(length=8), nullable=False),
    sa.Column('goal_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['life_path_id'], ['life_path.id'], ),
    sa.PrimaryKeyConstraint('learner_id')
    )
    op.create_index(op.f('ix_learner_profile_life_path_id'), 'learner_profile', ['life_path_id'], unique=False)
    op.create_table('life_path_context',
    sa.Column('life_path_id', sa.String(length=48), nullable=False),
    sa.Column('from_context', sa.Text(), nullable=False),
    sa.Column('to_context', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['life_path_id'], ['life_path.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('life_path_id', 'from_context')
    )
    op.create_table('life_path_domain',
    sa.Column('life_path_id', sa.String(length=48), nullable=False),
    sa.Column('domain_id', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['life_path_id'], ['life_path.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('life_path_id', 'domain_id')
    )
    op.create_table('life_path_template_pref',
    sa.Column('life_path_id', sa.String(length=48), nullable=False),
    sa.Column('template_id', sa.String(length=8), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['life_path_id'], ['life_path.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('life_path_id', 'template_id')
    )
    op.create_table('stimulus_pool',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('template_id', sa.String(length=8), nullable=False),
    sa.Column('target_set_key', sa.String(length=200), nullable=False),
    sa.Column('theme', sa.String(length=200), nullable=False),
    sa.Column('stimulus_type', sa.String(length=32), nullable=False),
    sa.Column('asset_url', sa.Text(), nullable=True),
    sa.Column('spec_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'target_set_key', 'theme', name='stimulus_pool_key_uq')
    )
    op.create_index(op.f('ix_stimulus_pool_target_set_key'), 'stimulus_pool', ['target_set_key'], unique=False)
    op.create_index(op.f('ix_stimulus_pool_theme'), 'stimulus_pool', ['theme'], unique=False)
    op.create_table('template_elicits',
    sa.Column('template_id', sa.String(length=8), nullable=False),
    sa.Column('competency_id', sa.String(length=16), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint('strength >= 0 and strength <= 1', name='template_elicits_range_check'),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('template_id', 'competency_id')
    )
    op.create_table('template_measures',
    sa.Column('template_id', sa.String(length=8), nullable=False),
    sa.Column('skill', sa.Enum('vocabulary', 'grammar', 'pronunciation', 'fluency', name='measures_skill', native_enum=False), nullable=False),
    sa.Column('reliability', sa.Float(), nullable=False),
    sa.CheckConstraint('reliability >= 0 and reliability <= 1', name='template_measures_range_check'),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('template_id', 'skill')
    )
    op.create_table('template_requires',
    sa.Column('template_id', sa.String(length=8), nullable=False),
    sa.Column('competency_id', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['competency_id'], ['competency.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('template_id', 'competency_id'),
    sa.UniqueConstraint('template_id', 'competency_id', name='template_requires_uq')
    )
    op.create_table('day_plan',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('learner_id', sa.String(length=48), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('domain_id', sa.String(length=16), nullable=False),
    sa.Column('theme', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profile.learner_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'date', name='day_plan_learner_date_uq')
    )
    op.create_index(op.f('ix_day_plan_learner_id'), 'day_plan', ['learner_id'], unique=False)
    op.create_table('dimension_member',
    sa.Column('dimension_id', sa.String(length=48), nullable=False),
    sa.Column('competency_pattern', sa.String(length=16), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['dimension_id'], ['dimension.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dimension_id', 'competency_pattern')
    )
    op.create_table('learner_competency',
    sa.Column('learner_id', sa.String(length=48), nullable=False),
    sa.Column('competency_id', sa.String(length=16), nullable=False),
    sa.Column('mastery', sa.Float(), nullable=False),
    sa.Column('stability_days', sa.Float(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_template', sa.String(length=8), nullable=True),
    sa.Column('last_theme', sa.String(length=200), nullable=True),
    sa.CheckConstraint('mastery >= 0 and mastery <= 1', name='learner_competency_mastery_check'),
    sa.CheckConstraint('stability_days > 0', name='learner_competency_stability_check'),
    sa.ForeignKeyConstraint(['competency_id'], ['competency.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profile.learner_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('learner_id', 'competency_id')
    )
    op.create_table('learner_error',
    sa.Column('learner_id', sa.String(length=48), nullable=False),
    sa.Column('competency_id', sa.String(length=16), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['competency_id'], ['competency.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['learner_id'], ['learner_profile.learner_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('learner_id', 'competency_id', 'tag')
    )
    op.create_table('session',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('day_plan_id', sa.String(length=64), nullable=False),
    sa.Column('template_id', sa.String(length=8), nullable=False),
    sa.Column('stimulus_id', sa.String(length=64), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('skill_focus', sa.String(length=16), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('spec_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['day_plan_id'], ['day_plan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stimulus_id'], ['stimulus_pool.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_day_plan_id'), 'session', ['day_plan_id'], unique=False)
    op.create_table('reflection',
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('learner_text', sa.Text(), nullable=False),
    sa.Column('matched_error_tag', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('session_target',
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('competency_id', sa.String(length=16), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Float(), nullable=True),
    sa.CheckConstraint("role in ('new','review','incidental')", name='session_target_role_check'),
    sa.ForeignKeyConstraint(['competency_id'], ['competency.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'competency_id')
    )
    op.create_table('turn',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('audio_url', sa.Text(), nullable=True),
    sa.Column('transcript_verbatim', sa.Text(), nullable=True),
    sa.Column('transcript_clean', sa.Text(), nullable=True),
    sa.Column('metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scaffold_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'index', name='turn_session_index_uq')
    )
    op.create_index(op.f('ix_turn_session_id'), 'turn', ['session_id'], unique=False)
    op.create_table('attempt',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('turn_id', sa.String(length=64), nullable=False),
    sa.Column('competency_id', sa.String(length=16), nullable=False),
    sa.Column('opportunities', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Integer(), nullable=False),
    sa.Column('error_tags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scaffold_level', sa.Integer(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('correct >= 0 and correct <= opportunities', name='attempt_correct_range_check'),
    sa.CheckConstraint('opportunities >= 0', name='attempt_opportunities_check'),
    sa.ForeignKeyConstraint(['competency_id'], ['competency.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_id'], ['turn.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('turn_id', 'competency_id', name='attempt_turn_competency_uq')
    )
    op.create_index(op.f('ix_attempt_competency_id'), 'attempt', ['competency_id'], unique=False)
    op.create_index(op.f('ix_attempt_turn_id'), 'attempt', ['turn_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attempt_turn_id'), table_name='attempt')
    op.drop_index(op.f('ix_attempt_competency_id'), table_name='attempt')
    op.drop_table('attempt')
    op.drop_index(op.f('ix_turn_session_id'), table_name='turn')
    op.drop_table('turn')
    op.drop_table('session_target')
    op.drop_table('reflection')
    op.drop_index(op.f('ix_session_day_plan_id'), table_name='session')
    op.drop_table('session')
    op.drop_table('learner_error')
    op.drop_table('learner_competency')
    op.drop_table('dimension_member')
    op.drop_index(op.f('ix_day_plan_learner_id'), table_name='day_plan')
    op.drop_table('day_plan')
    op.drop_table('template_requires')
    op.drop_table('template_measures')
    op.drop_table('template_elicits')
    op.drop_index(op.f('ix_stimulus_pool_theme'), table_name='stimulus_pool')
    op.drop_index(op.f('ix_stimulus_pool_target_set_key'), table_name='stimulus_pool')
    op.drop_table('stimulus_pool')
    op.drop_table('life_path_template_pref')
    op.drop_table('life_path_domain')
    op.drop_table('life_path_context')
    op.drop_index(op.f('ix_learner_profile_life_path_id'), table_name='learner_profile')
    op.drop_table('learner_profile')
    op.drop_table('domain_requires')
    op.drop_index(op.f('ix_domain_objective_domain_id'), table_name='domain_objective')
    op.drop_table('domain_objective')
    op.drop_index(op.f('ix_domain_context_domain_id'), table_name='domain_context')
    op.drop_table('domain_context')
    op.drop_index(op.f('ix_dimension_life_path_id'), table_name='dimension')
    op.drop_table('dimension')
    op.drop_table('competency_prereq')
    op.drop_index(op.f('ix_competency_error_tag'), table_name='competency_error')
    op.drop_index(op.f('ix_competency_error_competency_id'), table_name='competency_error')
    op.drop_table('competency_error')
    op.drop_table('template')
    op.drop_table('life_path')
    op.drop_table('domain')
    op.drop_index(op.f('ix_competency_parent'), table_name='competency')
    op.drop_table('competency')
    # ### end Alembic commands ###
