/**
 * Drawn stand-ins for Stimulus Pool assets.
 *
 * In production every image is generated by the fal image model from the
 * template's `elicitation_cues` and the Life Path theme, and generated *again*
 * next time — reviewing a competency "in a new context" means a new picture,
 * which is the whole reason the pool exists. These scenes exist so the
 * component layer, the layout and the demo can be built and reviewed before
 * that pipeline does.
 *
 * They are drawn rather than photographed for one reason beyond cost: a
 * describable picture needs unambiguous, nameable objects. A photograph is
 * full of things an A2 learner has no word for, and the evaluator would score
 * the omission as a vocabulary gap.
 *
 * Each scene names what it contains, because that list is the ceiling on what
 * the learner can be expected to say.
 */

import { type SceneId } from "./scene-ids";

export { sceneIds, type SceneId } from "./scene-ids";

export interface Scene {
  id: SceneId;
  /** For screen readers, and for the evaluator's expected-vocabulary set. */
  description: string;
  render: () => React.ReactNode;
}

const VIEWBOX = "0 0 400 260";

/** Shared defs — every scene draws on the same sky, ground and light. */
function Defs({ prefix }: { prefix: string }) {
  return (
    <defs>
      <linearGradient id={`${prefix}-sky`} x1="0" y1="0" x2="0" y2="1">
        <stop offset="0%" stopColor="oklch(0.94 0.035 232)" />
        <stop offset="100%" stopColor="oklch(0.985 0.012 300)" />
      </linearGradient>
      <linearGradient id={`${prefix}-ground`} x1="0" y1="0" x2="0" y2="1">
        <stop offset="0%" stopColor="oklch(0.9 0.03 150)" />
        <stop offset="100%" stopColor="oklch(0.84 0.045 150)" />
      </linearGradient>
      <linearGradient id={`${prefix}-wall`} x1="0" y1="0" x2="1" y2="0">
        <stop offset="0%" stopColor="oklch(0.9 0.012 265)" />
        <stop offset="100%" stopColor="oklch(0.82 0.016 265)" />
      </linearGradient>
      <linearGradient id={`${prefix}-indoor`} x1="0" y1="0" x2="0" y2="1">
        <stop offset="0%" stopColor="oklch(0.95 0.014 70)" />
        <stop offset="100%" stopColor="oklch(0.89 0.022 60)" />
      </linearGradient>
    </defs>
  );
}

/** A person, seated or standing, in one call. */
function Person({
  x,
  y,
  skin,
  shirt,
  seated = false,
  scale = 1,
}: {
  x: number;
  y: number;
  skin: string;
  shirt: string;
  seated?: boolean;
  scale?: number;
}) {
  const torso = seated ? 30 : 50;
  return (
    <g transform={`translate(${x} ${y}) scale(${scale})`}>
      <circle cx="0" cy="0" r="10" fill={skin} />
      <path d={`M-10 ${torso}v-${torso - 4}a10 10 0 0 1 20 0v${torso}z`} fill={shirt} />
      <rect
        x="-9"
        y={torso - 2}
        width="18"
        height={seated ? 10 : 24}
        rx={seated ? 3 : 4}
        fill="oklch(0.42 0.04 265)"
      />
    </g>
  );
}

function CampusCourtyard() {
  return (
    <>
      <Defs prefix="cc" />
      <rect width="400" height="260" fill="url(#cc-sky)" />
      <circle cx="330" cy="46" r="20" fill="oklch(0.96 0.06 95)" opacity="0.75" />

      <rect x="232" y="42" width="128" height="150" fill="url(#cc-wall)" />
      <rect x="232" y="42" width="128" height="9" fill="oklch(0.75 0.02 265)" />
      {[0, 1, 2, 3].map((row) =>
        [0, 1, 2, 3].map((col) => (
          <rect
            key={`${row}-${col}`}
            x={246 + col * 28}
            y={64 + row * 30}
            width="18"
            height="20"
            rx="2"
            fill="oklch(0.88 0.05 232)"
            opacity={(row + col) % 3 === 0 ? 0.95 : 0.65}
          />
        )),
      )}
      <rect x="286" y="160" width="24" height="32" rx="3" fill="oklch(0.7 0.03 265)" />

      {/* Noticeboard */}
      <rect x="196" y="96" width="30" height="42" rx="3" fill="oklch(0.72 0.06 60)" />
      <rect x="200" y="100" width="22" height="34" rx="2" fill="oklch(0.97 0.008 90)" />
      <rect x="203" y="105" width="16" height="3" rx="1.5" fill="oklch(0.8 0.04 265)" />
      <rect x="203" y="112" width="12" height="3" rx="1.5" fill="oklch(0.8 0.04 265)" />
      <rect x="203" y="119" width="15" height="3" rx="1.5" fill="oklch(0.8 0.04 265)" />

      <rect x="0" y="192" width="400" height="68" fill="url(#cc-ground)" />
      <ellipse cx="200" cy="196" rx="200" ry="8" fill="oklch(0.88 0.03 150)" />

      {/* Jacaranda */}
      <rect x="86" y="120" width="9" height="74" rx="3" fill="oklch(0.6 0.05 60)" />
      <circle cx="90" cy="98" r="42" fill="oklch(0.74 0.12 305)" opacity="0.9" />
      <circle cx="62" cy="112" r="26" fill="oklch(0.78 0.1 305)" opacity="0.85" />
      <circle cx="118" cy="110" r="28" fill="oklch(0.7 0.13 300)" opacity="0.85" />

      {/* Bench */}
      <rect x="60" y="170" width="96" height="8" rx="3" fill="oklch(0.66 0.06 60)" />
      <rect x="68" y="178" width="6" height="16" rx="2" fill="oklch(0.58 0.05 60)" />
      <rect x="142" y="178" width="6" height="16" rx="2" fill="oklch(0.58 0.05 60)" />

      <Person x={84} y={140} skin="oklch(0.56 0.05 45)" shirt="oklch(0.62 0.16 25)" seated />
      <rect x="72" y="158" width="16" height="11" rx="2" fill="oklch(0.97 0.01 90)" />
      <Person x={126} y={140} skin="oklch(0.5 0.045 45)" shirt="oklch(0.62 0.11 222)" seated />
      <rect x="122" y="156" width="18" height="12" rx="2" fill="oklch(0.85 0.02 265)" />

      <Person x={176} y={122} skin="oklch(0.54 0.05 45)" shirt="oklch(0.6 0.14 152)" />
      <rect
        x="185"
        y="126"
        width="20"
        height="6"
        rx="3"
        fill="oklch(0.54 0.05 45)"
        transform="rotate(-14 185 126)"
      />
    </>
  );
}

function CafeCounter() {
  return (
    <>
      <Defs prefix="cf" />
      <rect width="400" height="260" fill="url(#cf-indoor)" />

      {/* Back wall, menu board, shelves */}
      <rect x="0" y="0" width="400" height="150" fill="oklch(0.91 0.02 60)" />
      <rect x="238" y="26" width="130" height="62" rx="4" fill="oklch(0.36 0.03 60)" />
      {[0, 1, 2, 3].map((i) => (
        <rect
          key={i}
          x={250}
          y={38 + i * 13}
          width={i % 2 ? 78 : 96}
          height="5"
          rx="2.5"
          fill="oklch(0.85 0.02 60)"
          opacity="0.75"
        />
      ))}
      <rect x="40" y="46" width="140" height="6" rx="3" fill="oklch(0.72 0.05 60)" />
      {[0, 1, 2, 3, 4].map((i) => (
        <rect
          key={i}
          x={48 + i * 27}
          y={28}
          width="16"
          height="18"
          rx="3"
          fill={i % 2 ? "oklch(0.72 0.1 30)" : "oklch(0.78 0.07 150)"}
        />
      ))}

      {/* Counter */}
      <rect x="0" y="150" width="400" height="18" fill="oklch(0.55 0.05 55)" />
      <rect x="0" y="168" width="400" height="92" fill="oklch(0.72 0.045 55)" />

      {/* Espresso machine and cups */}
      <rect x="238" y="112" width="62" height="38" rx="4" fill="oklch(0.7 0.02 265)" />
      <rect x="248" y="122" width="42" height="14" rx="2" fill="oklch(0.5 0.02 265)" />
      <rect x="150" y="132" width="16" height="18" rx="3" fill="oklch(0.97 0.01 90)" />
      <rect x="150" y="132" width="16" height="5" rx="2" fill="oklch(0.7 0.09 30)" />
      <ellipse cx="196" cy="148" rx="18" ry="5" fill="oklch(0.86 0.02 60)" />
      <rect x="182" y="138" width="28" height="10" rx="3" fill="oklch(0.93 0.02 90)" />

      {/* Barista behind, customer in front */}
      <Person x={300} y={92} skin="oklch(0.5 0.045 45)" shirt="oklch(0.45 0.03 265)" />
      <Person x={96} y={104} skin="oklch(0.58 0.05 45)" shirt="oklch(0.64 0.13 25)" scale={1.12} />

      {/* Card in the customer's hand */}
      <rect x="112" y="146" width="18" height="12" rx="2" fill="oklch(0.7 0.1 250)" />
    </>
  );
}

function MarketStall() {
  return (
    <>
      <Defs prefix="mk" />
      <rect width="400" height="260" fill="url(#mk-sky)" />
      <rect x="0" y="192" width="400" height="68" fill="url(#mk-ground)" />

      {/* Awning */}
      <path d="M30 70h340l-16 34H46z" fill="oklch(0.7 0.13 25)" />
      {[0, 1, 2, 3, 4, 5].map((i) => (
        <path
          key={i}
          d={`M${58 + i * 56} 70h28l-13 34h-28z`}
          fill="oklch(0.95 0.02 90)"
          opacity="0.85"
        />
      ))}
      <rect x="44" y="104" width="7" height="90" fill="oklch(0.6 0.05 60)" />
      <rect x="349" y="104" width="7" height="90" fill="oklch(0.6 0.05 60)" />

      {/* Table of produce */}
      <rect x="56" y="150" width="288" height="12" rx="3" fill="oklch(0.62 0.055 60)" />
      <rect x="56" y="162" width="288" height="32" fill="oklch(0.72 0.045 60)" />
      {[
        { x: 84, fill: "oklch(0.72 0.15 30)" },
        { x: 132, fill: "oklch(0.78 0.14 95)" },
        { x: 180, fill: "oklch(0.68 0.14 150)" },
        { x: 228, fill: "oklch(0.66 0.13 20)" },
        { x: 276, fill: "oklch(0.8 0.12 75)" },
      ].map((crate) => (
        <g key={crate.x}>
          <rect x={crate.x - 20} y="132" width="40" height="18" rx="3" fill="oklch(0.66 0.05 60)" />
          {[0, 1, 2].map((i) => (
            <circle key={i} cx={crate.x - 11 + i * 11} cy="130" r="7" fill={crate.fill} />
          ))}
        </g>
      ))}

      {/* Vendor behind the table, shopper in front with a bag */}
      <Person x={300} y={104} skin="oklch(0.5 0.045 45)" shirt="oklch(0.6 0.12 152)" />
      <Person x={110} y={112} skin="oklch(0.57 0.05 45)" shirt="oklch(0.6 0.13 285)" scale={1.1} />
      <rect x="128" y="152" width="22" height="26" rx="3" fill="oklch(0.8 0.06 95)" />
      <path d="M132 152v-6a7 7 0 0 1 14 0v6" stroke="oklch(0.65 0.05 95)" strokeWidth="2.5" fill="none" />
    </>
  );
}

function HotelLobby() {
  return (
    <>
      <Defs prefix="hl" />
      <rect width="400" height="260" fill="url(#hl-indoor)" />
      <rect x="0" y="0" width="400" height="160" fill="oklch(0.93 0.014 265)" />

      {/* Feature wall and signage */}
      <rect x="150" y="24" width="110" height="46" rx="4" fill="oklch(0.88 0.02 265)" />
      <rect x="166" y="42" width="78" height="8" rx="4" fill="oklch(0.6 0.04 265)" />
      <rect x="30" y="30" width="72" height="96" rx="4" fill="oklch(0.86 0.05 232)" />
      <rect x="298" y="30" width="72" height="96" rx="4" fill="oklch(0.86 0.05 232)" />

      {/* Reception desk */}
      <rect x="96" y="150" width="208" height="16" rx="3" fill="oklch(0.52 0.05 55)" />
      <rect x="96" y="166" width="208" height="60" fill="oklch(0.7 0.045 55)" />
      <rect x="120" y="128" width="26" height="22" rx="3" fill="oklch(0.5 0.02 265)" />
      <rect x="124" y="132" width="18" height="12" rx="1.5" fill="oklch(0.85 0.05 232)" />
      {/* Bell */}
      <path d="M262 150a10 10 0 0 1 20 0z" fill="oklch(0.8 0.09 90)" />

      {/* Receptionist and guest with a suitcase */}
      <Person x={200} y={98} skin="oklch(0.5 0.045 45)" shirt="oklch(0.42 0.04 265)" />
      <Person x={334} y={116} skin="oklch(0.58 0.05 45)" shirt="oklch(0.64 0.12 25)" scale={1.05} />
      <rect x="352" y="176" width="26" height="34" rx="4" fill="oklch(0.55 0.06 250)" />
      <rect x="360" y="164" width="10" height="14" rx="3" fill="oklch(0.5 0.03 250)" />

      <rect x="0" y="226" width="400" height="34" fill="oklch(0.82 0.02 60)" />
    </>
  );
}

function CrowdedBus() {
  return (
    <>
      <Defs prefix="bs" />
      <rect width="400" height="260" fill="url(#bs-indoor)" />
      <rect x="0" y="0" width="400" height="176" fill="oklch(0.9 0.02 232)" />

      {/* Windows */}
      {[0, 1, 2].map((i) => (
        <rect
          key={i}
          x={30 + i * 120}
          y={34}
          width="94"
          height="62"
          rx="8"
          fill="oklch(0.88 0.055 232)"
        />
      ))}

      {/* Handrail and straps */}
      <rect x="16" y="108" width="368" height="6" rx="3" fill="oklch(0.72 0.02 265)" />
      {[0, 1, 2, 3, 4].map((i) => (
        <rect
          key={i}
          x={62 + i * 68}
          y={114}
          width="4"
          height="24"
          rx="2"
          fill="oklch(0.68 0.03 60)"
        />
      ))}

      {/* Seats */}
      <rect x="0" y="176" width="400" height="84" fill="oklch(0.8 0.03 60)" />
      {[0, 1, 2].map((i) => (
        <rect
          key={i}
          x={24 + i * 128}
          y={182}
          width="104"
          height="42"
          rx="6"
          fill="oklch(0.6 0.08 285)"
        />
      ))}

      <Person x={76} y={152} skin="oklch(0.55 0.05 45)" shirt="oklch(0.62 0.13 25)" seated />
      <Person x={204} y={152} skin="oklch(0.5 0.045 45)" shirt="oklch(0.6 0.12 152)" seated />
      <Person x={330} y={126} skin="oklch(0.57 0.05 45)" shirt="oklch(0.6 0.11 250)" />
    </>
  );
}

function QuietLibrary() {
  return (
    <>
      <Defs prefix="lb" />
      <rect width="400" height="260" fill="url(#lb-indoor)" />
      <rect x="0" y="0" width="400" height="170" fill="oklch(0.92 0.018 70)" />

      {/* Shelves */}
      {[0, 1].map((shelf) => (
        <g key={shelf}>
          <rect x={20 + shelf * 210} y="24" width="150" height="112" rx="4" fill="oklch(0.6 0.055 55)" />
          {[0, 1, 2].map((row) => (
            <g key={row}>
              <rect
                x={26 + shelf * 210}
                y={30 + row * 36}
                width="138"
                height="30"
                fill="oklch(0.84 0.03 60)"
              />
              {Array.from({ length: 9 }).map((_, b) => (
                <rect
                  key={b}
                  x={30 + shelf * 210 + b * 15}
                  y={34 + row * 36}
                  width={9}
                  height={22 - ((b + row) % 3) * 3}
                  rx="1.5"
                  fill={
                    ["oklch(0.6 0.12 25)", "oklch(0.58 0.1 250)", "oklch(0.62 0.11 150)", "oklch(0.68 0.11 90)"][
                      (b + row + shelf) % 4
                    ]
                  }
                />
              ))}
            </g>
          ))}
        </g>
      ))}

      {/* Table with a lamp, books and a laptop */}
      <rect x="0" y="170" width="400" height="90" fill="oklch(0.86 0.022 70)" />
      <rect x="70" y="186" width="260" height="12" rx="3" fill="oklch(0.5 0.05 55)" />
      <rect x="90" y="198" width="10" height="44" fill="oklch(0.45 0.04 55)" />
      <rect x="300" y="198" width="10" height="44" fill="oklch(0.45 0.04 55)" />
      <rect x="112" y="170" width="34" height="16" rx="2" fill="oklch(0.7 0.09 30)" />
      <rect x="116" y="164" width="34" height="6" rx="2" fill="oklch(0.62 0.11 250)" />
      <path d="M236 186l24-14 24 14z" fill="oklch(0.72 0.02 265)" />
      <rect x="246" y="170" width="28" height="16" rx="2" fill="oklch(0.86 0.04 232)" />

      <Person x={186} y={126} skin="oklch(0.54 0.05 45)" shirt="oklch(0.58 0.1 285)" seated />
    </>
  );
}

export const scenes: Record<SceneId, Scene> = {
  campus_courtyard: {
    id: "campus_courtyard",
    description:
      "A university courtyard. Two students sit on a bench with books and a laptop while a third stands pointing at a noticeboard, under a tree beside a tall building.",
    render: CampusCourtyard,
  },
  cafe_counter: {
    id: "cafe_counter",
    description:
      "A cafe counter. A customer holding a card stands in front of the till while a barista works at the coffee machine, under a menu board.",
    render: CafeCounter,
  },
  market_stall: {
    id: "market_stall",
    description:
      "A market stall under a striped awning. A vendor stands behind crates of fruit and vegetables while a shopper carrying a bag looks at the produce.",
    render: MarketStall,
  },
  hotel_lobby: {
    id: "hotel_lobby",
    description:
      "A hotel lobby. A receptionist stands behind the desk with a computer and a bell, while a guest arrives pulling a suitcase.",
    render: HotelLobby,
  },
  crowded_bus: {
    id: "crowded_bus",
    description:
      "The inside of a busy bus. Two passengers sit by the windows and one stands holding the rail.",
    render: CrowdedBus,
  },
  quiet_library: {
    id: "quiet_library",
    description:
      "A library. Someone sits at a long table with a laptop, a lamp and a stack of books, between two tall bookshelves.",
    render: QuietLibrary,
  },
};

/** The raw SVG for a scene, sized by its container. */
export function SceneSvg({ id, className }: { id: SceneId; className?: string }) {
  const scene = scenes[id];
  return (
    <svg viewBox={VIEWBOX} className={className} role="img" aria-label={scene.description}>
      {scene.render()}
    </svg>
  );
}
