"use client";

import { cn } from "@/lib/utils";

/**
 * The picture in a picture-description session.
 *
 * In production this is an asset from the Stimulus Pool, generated by the fal
 * image model from the template's `elicitation_cues` and the Life Path theme,
 * and a new one every time — reviewing a competency "in a new context" means a
 * new asset. Until that pipeline exists the scene below stands in, drawn
 * rather than photographed so it costs nothing to ship and still gives the
 * learner concrete things to name: people, a bench, books, a tree, a building.
 */
export function StimulusImage({ className }: { className?: string }) {
  return (
    <figure
      className={cn(
        "surface-panel overflow-hidden rounded-2xl p-1.5 shadow-[0_18px_50px_-28px_oklch(0.4_0.06_280/45%)]",
        className,
      )}
    >
      <CampusCourtyard />
      <figcaption className="sr-only">
        A university courtyard. Two students sit on a bench with books and a
        laptop while a third stands pointing at a noticeboard, under a tree
        beside a tall building.
      </figcaption>
    </figure>
  );
}

function CampusCourtyard() {
  return (
    <svg
      viewBox="0 0 400 260"
      className="block h-auto w-full rounded-[0.875rem]"
      role="img"
      aria-label="A university courtyard with students on a bench"
    >
      <defs>
        <linearGradient id="sky" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stopColor="oklch(0.94 0.035 232)" />
          <stop offset="100%" stopColor="oklch(0.985 0.012 300)" />
        </linearGradient>
        <linearGradient id="ground" x1="0" y1="0" x2="0" y2="1">
          <stop offset="0%" stopColor="oklch(0.9 0.03 150)" />
          <stop offset="100%" stopColor="oklch(0.84 0.045 150)" />
        </linearGradient>
        <linearGradient id="tower" x1="0" y1="0" x2="1" y2="0">
          <stop offset="0%" stopColor="oklch(0.9 0.012 265)" />
          <stop offset="100%" stopColor="oklch(0.82 0.016 265)" />
        </linearGradient>
      </defs>

      <rect width="400" height="260" fill="url(#sky)" />
      <circle cx="330" cy="46" r="20" fill="oklch(0.96 0.06 95)" opacity="0.75" />

      {/* Building */}
      <rect x="232" y="42" width="128" height="150" fill="url(#tower)" />
      <rect x="232" y="42" width="128" height="9" fill="oklch(0.75 0.02 265)" />
      {[0, 1, 2, 3].map((row) =>
        [0, 1, 2, 3].map((col) => (
          <rect
            key={`${row}-${col}`}
            x={246 + col * 28}
            y={64 + row * 30}
            width="18"
            height="20"
            rx="2"
            fill="oklch(0.88 0.05 232)"
            opacity={(row + col) % 3 === 0 ? 0.95 : 0.65}
          />
        )),
      )}
      <rect x="286" y="160" width="24" height="32" rx="3" fill="oklch(0.7 0.03 265)" />

      {/* Noticeboard */}
      <rect x="196" y="96" width="30" height="42" rx="3" fill="oklch(0.72 0.06 60)" />
      <rect x="200" y="100" width="22" height="34" rx="2" fill="oklch(0.97 0.008 90)" />
      <rect x="203" y="105" width="16" height="3" rx="1.5" fill="oklch(0.8 0.04 265)" />
      <rect x="203" y="112" width="12" height="3" rx="1.5" fill="oklch(0.8 0.04 265)" />
      <rect x="203" y="119" width="15" height="3" rx="1.5" fill="oklch(0.8 0.04 265)" />

      {/* Ground */}
      <rect x="0" y="192" width="400" height="68" fill="url(#ground)" />
      <ellipse cx="200" cy="196" rx="200" ry="8" fill="oklch(0.88 0.03 150)" />

      {/* Jacaranda */}
      <rect x="86" y="120" width="9" height="74" rx="3" fill="oklch(0.6 0.05 60)" />
      <circle cx="90" cy="98" r="42" fill="oklch(0.74 0.12 305)" opacity="0.9" />
      <circle cx="62" cy="112" r="26" fill="oklch(0.78 0.1 305)" opacity="0.85" />
      <circle cx="118" cy="110" r="28" fill="oklch(0.7 0.13 300)" opacity="0.85" />
      <circle cx="46" cy="186" r="3" fill="oklch(0.74 0.12 305)" />
      <circle cx="132" cy="190" r="2.5" fill="oklch(0.74 0.12 305)" />

      {/* Bench */}
      <rect x="60" y="170" width="96" height="8" rx="3" fill="oklch(0.66 0.06 60)" />
      <rect x="68" y="178" width="6" height="16" rx="2" fill="oklch(0.58 0.05 60)" />
      <rect x="142" y="178" width="6" height="16" rx="2" fill="oklch(0.58 0.05 60)" />

      {/* Seated student, left */}
      <circle cx="84" cy="140" r="10" fill="oklch(0.56 0.05 45)" />
      <path d="M74 170v-16a10 10 0 0 1 20 0v16z" fill="oklch(0.62 0.16 25)" />
      <rect x="76" y="168" width="18" height="10" rx="3" fill="oklch(0.45 0.05 265)" />
      <rect x="72" y="158" width="16" height="11" rx="2" fill="oklch(0.97 0.01 90)" />

      {/* Seated student, right */}
      <circle cx="126" cy="140" r="10" fill="oklch(0.5 0.045 45)" />
      <path d="M116 170v-16a10 10 0 0 1 20 0v16z" fill="oklch(0.62 0.11 222)" />
      <rect x="118" y="168" width="18" height="10" rx="3" fill="oklch(0.42 0.04 265)" />
      <rect x="122" y="156" width="18" height="12" rx="2" fill="oklch(0.85 0.02 265)" />

      {/* Standing student pointing at the noticeboard */}
      <circle cx="176" cy="122" r="11" fill="oklch(0.54 0.05 45)" />
      <path d="M165 172v-32a11 11 0 0 1 22 0v32z" fill="oklch(0.6 0.14 152)" />
      <rect x="167" y="170" width="18" height="24" rx="4" fill="oklch(0.4 0.04 265)" />
      <rect
        x="185"
        y="126"
        width="20"
        height="6"
        rx="3"
        fill="oklch(0.54 0.05 45)"
        transform="rotate(-14 185 126)"
      />
      {/* Coffee cup in the other hand */}
      <rect x="156" y="146" width="8" height="11" rx="2" fill="oklch(0.97 0.01 90)" />
      <rect x="156" y="146" width="8" height="3" rx="1" fill="oklch(0.7 0.09 30)" />
    </svg>
  );
}
